### ISSUE TITLE
portrait photos are sent landscaped

### ISSUE THREAD

**Issue by legacychimera247** [neochapay/Prostogram#28]
when i upload a photo in portrait it automatically gets rotated to landscape and there's no way to change this...it should have at least a way to rotate the photo :)

**Comment by legacychimera247** [comment]
you can't fix that?or you just can't at the moment?

**Comment by neochapay** [comment]
Yes i add rotate button on edit page

**Comment by legacychimera247** [comment]
ok that's good :)
