### ISSUE TITLE
folling/followers are not working

### ISSUE THREAD

**Issue by legacychimera247** [neochapay/Prostogram#29]
as the title said there is a pulley for seeing followers and who we follow but after we enter that menù there is only the loading circle spinning forever...

**Comment by neochapay** [comment]
version ?

**Comment by legacychimera247** [comment]
version 8.1...the one that landed in the store today

**Comment by neochapay** [comment]
On my phone work correct.....

**Comment by legacychimera247** [comment]
so i will try to logout then clean the cache

**Comment by legacychimera247** [comment]
so...logged out, then uninstalled the app, then deleted folders in cache and local then rebooted and installed again...but i still have just the circle spinning...

**Comment by neochapay** [comment]
ok....i recheck...

**Comment by legacychimera247** [comment]
now they are working so i think i can close this one...the only thing is...seems that italian tranlsation for following/followers seems swapped...accept me on transifex for the translation and i will fix that together with the rest of the translation :)
