### ISSUE TITLE
Can't send screenshots

### ISSUE THREAD

**Issue by Hamool** [neochapay/Prostogram#3]
I can't send screenshots (I guess, that's also true for any vertical pictures with 16:9 or similar aspect ratio) from your app. The 'send' button appears to be out of the screen space and I can't scroll to reach it.

Also, liking photos by double tapping on them would be nice :)

![_ _20160805_002](https://cloud.githubusercontent.com/assets/13868666/17429973/dd5e18de-5b1b-11e6-91a1-78ef102e2a09.png)

**Comment by neochapay** [comment]
Fix on 0.8.1
