### ISSUE TITLE
uploading a photo result in a cropped photo

### ISSUE THREAD

**Issue by legacychimera247** [neochapay/Prostogram#30]
if you upload a photo through prostogram your photo will be automatically cropped at the bottom and there will be a black bar on the top...so atm it's impossible to upload photos with prostogram

**Comment by neochapay** [comment]
Check in last version plz

**Comment by legacychimera247** [comment]
i have the last version from jolla store...this is the photo i want to upload : 
https://1drv.ms/i/s!AlyMkCypv00qgr5iokSMbNdaB6KaOg
this is the result i get : 
https://1drv.ms/i/s!AlyMkCypv00qgr5gFIQauFBJ-u_7RQ

don't think version from store and openrepos are different, right?
