### ISSUE TITLE
help in translating

### ISSUE THREAD

**Issue by legacychimera247** [neochapay/Prostogram#33]
as the title says i would like to help translating the app in italian...any way to do so? :)

**Comment by neochapay** [comment]
you can get PR

**Comment by legacychimera247** [comment]
what does this mean?there are some pages like transifex i should sign for?

**Comment by neochapay** [comment]
https://www.transifex.com/neochapay/prostogram/

**Comment by legacychimera247** [comment]
thanks...requested the italian language since the help translating only had 9 languages but not italian
