### ISSUE TITLE
Instagram Stories

### ISSUE THREAD

**Issue by maidis** [neochapay/Prostogram#38]
Instagram recently added a Snapchat-like temporary/vanishing photo sharing feature. It would be nice to have this feature.

https://help.instagram.com/1660923094227526/
http://blog.instagram.com/post/148348940287/160802-stories

I don't know if Instagram API offers this feature. But I guess it can be done in some way:

https://github.com/CaliAlec/ChromeIGStory
https://chrome.google.com/webstore/detail/chrome-ig-story/bojgejgifofondahckoaahkilneffhmf

**Comment by legacychimera247** [comment]
already reported this in [https://github.com/neochapay/Prostogram/issues/31](url) and neochapay closed it due to a commit, so i thought this was fiex...but seems it isn't...
