### ISSUE TITLE
follow/unfollow 

### ISSUE THREAD

**Issue by DimaAsket** [neochapay/Prostogram#47]
follow unfollow not work

**Comment by DimaAsket** [comment]
I try to follow/unfollow some users from the bottom menu at user's page. And it dont't work.
Intex Aqua Fish, Inoi R7.

**Comment by wiktorek140** [comment]
@DimaAsket there was a mistake with logic responsible for follow/unfollow. here is quick fix: https://github.com/wiktorek140/Prostogram/commit/3b14cdd95f8cf8d5502c83e88367e76802b838f2#diff-046e154713fe9d78fbe03475fd3bcb55L311

 If u want, u can compile fixed version from my git ;)

**Comment by DimaAsket** [comment]
Already done
